//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacion.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CapaPresentacion.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _12774939_Photoroom {
            get {
                object obj = ResourceManager.GetObject("12774939-Photoroom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _891372_Photoroom {
            get {
                object obj = ResourceManager.GetObject("891372-Photoroom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_icon_or_logo_illustration_outline_black_style_free_vector_Photoroom {
            get {
                object obj = ResourceManager.GetObject("delete-icon-or-logo-illustration-outline-black-style-free-vector-Photoroom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_icon_or_logo_illustration_outline_black_style_free_vector_Photoroom1 {
            get {
                object obj = ResourceManager.GetObject("delete-icon-or-logo-illustration-outline-black-style-free-vector-Photoroom1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap direction_way_icon_concept_260nw_2218211689_Photoroom {
            get {
                object obj = ResourceManager.GetObject("direction-way-icon-concept-260nw-2218211689-Photoroom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap favpng_user_login {
            get {
                object obj = ResourceManager.GetObject("favpng_user-login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap favpng_user_login1 {
            get {
                object obj = ResourceManager.GetObject("favpng_user-login1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icone_x_avec_cercle_noir {
            get {
                object obj = ResourceManager.GetObject("icone-x-avec-cercle-noir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_bank_business_invoice_computer_icons_computer_software_bank_text_service_Photoroom {
            get {
                object obj = ResourceManager.GetObject("png-clipart-bank-business-invoice-computer-icons-computer-software-bank-text-serv" +
                        "ice-Photoroom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_cleaning_cleaner_maid_service_computer_icons_others_angle_bathroom_monochrome_Photoroom {
            get {
                object obj = ResourceManager.GetObject("png-transparent-cleaning-cleaner-maid-service-computer-icons-others-angle-bathroo" +
                        "m-monochrome-Photoroom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_cleaning_cleaner_maid_service_computer_icons_others_angle_bathroom_monochrome_Photoroom1 {
            get {
                object obj = ResourceManager.GetObject("png-transparent-cleaning-cleaner-maid-service-computer-icons-others-angle-bathroo" +
                        "m-monochrome-Photoroom1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_computer_icons_add_logo_desktop_wallpaper_add_thumbnail_Photoroom {
            get {
                object obj = ResourceManager.GetObject("png-transparent-computer-icons-add-logo-desktop-wallpaper-add-thumbnail-Photoroom" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_computer_icons_add_logo_desktop_wallpaper_add_thumbnail_Photoroom1 {
            get {
                object obj = ResourceManager.GetObject("png-transparent-computer-icons-add-logo-desktop-wallpaper-add-thumbnail-Photoroom" +
                        "1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_computer_icons_add_logo_desktop_wallpaper_add_thumbnail_Photoroom2 {
            get {
                object obj = ResourceManager.GetObject("png-transparent-computer-icons-add-logo-desktop-wallpaper-add-thumbnail-Photoroom" +
                        "2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_computer_icons_add_logo_desktop_wallpaper_add_thumbnail_Photoroom3 {
            get {
                object obj = ResourceManager.GetObject("png-transparent-computer-icons-add-logo-desktop-wallpaper-add-thumbnail-Photoroom" +
                        "3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_computer_icons_skype_icon_design_change_password_logo_internet_share_icon_Photoroom {
            get {
                object obj = ResourceManager.GetObject("png-transparent-computer-icons-skype-icon-design-change-password-logo-internet-sh" +
                        "are-icon-Photoroom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_computer_icons_skype_icon_design_change_password_logo_internet_share_icon_Photoroom1 {
            get {
                object obj = ResourceManager.GetObject("png-transparent-computer-icons-skype-icon-design-change-password-logo-internet-sh" +
                        "are-icon-Photoroom1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_edit_edit_doc_draw_editting_pen_and_paper_tool_write_project_management_icon_thumbnail_Photoroom {
            get {
                object obj = ResourceManager.GetObject("png-transparent-edit-edit-doc-draw-editting-pen-and-paper-tool-write-project-mana" +
                        "gement-icon-thumbnail-Photoroom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_edit_edit_doc_draw_editting_pen_and_paper_tool_write_project_management_icon_thumbnail_Photoroom1 {
            get {
                object obj = ResourceManager.GetObject("png-transparent-edit-edit-doc-draw-editting-pen-and-paper-tool-write-project-mana" +
                        "gement-icon-thumbnail-Photoroom1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_the_x_symbol_in_a_flat_circle_vector_png_image_15837510 {
            get {
                object obj = ResourceManager.GetObject("pngtree-the-x-symbol-in-a-flat-circle-vector-png-image_15837510", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_the_x_symbol_in_a_flat_circle_vector_png_image_158375101 {
            get {
                object obj = ResourceManager.GetObject("pngtree-the-x-symbol-in-a-flat-circle-vector-png-image_158375101", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_the_x_symbol_in_a_flat_circle_vector_png_image_158375102 {
            get {
                object obj = ResourceManager.GetObject("pngtree-the-x-symbol-in-a-flat-circle-vector-png-image_158375102", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
